### ISSUE TITLE
Filter instances by physical location

### ISSUE THREAD

**Issue by vashio** [TheKinrar/instances#61] opened 2018-08-19 08:00 UTC
User story: I don't want to join an instance that is physically hosted in a certain country (or countries).

**Comment by mpfaff** [comment] 2020-09-02 02:08
Possible duplicate of #13, although that only mentions adding it country as a field.

**Comment by TheKinrar** [comment] 2022-11-21 04:53
Duplicate of #13

**Closed by TheKinrar** 2022-11-21 04:53 UTC
Labels: enhancement
