### ISSUE TITLE
Pleroma versions

### ISSUE THREAD

**Issue by tusooa** [TheKinrar/instances#108] opened 2022-07-23 01:18 UTC
Pleroma has a version string in /api/v1/instance that looks like:

```
"version": "2.7.2 (compatible; Pleroma 2.4.3-0-gaa31f7a19)"
```

( https://docs-develop.pleroma.social/backend/development/API/differences_in_mastoapi_responses/ )

**Comment by tusooa** [comment] 2022-08-20 01:42
Although some days ago I dreamed about this being fixed, it hasn't.

**Comment by TheKinrar** [comment] 2022-11-21 09:43
Duplicate of #51

**Closed by TheKinrar** 2022-11-21 09:43 UTC
Labels: enhancement
