### ISSUE TITLE
Accomodate peertube as well

### ISSUE THREAD

**Issue by mmahmoudian** [TheKinrar/instances#107] opened 2022-04-25 19:07 UTC
Peertube has also "similar" structure as Mastodon, each instance has its own Code of Conduct and can have language and registration preferences and configurations, therefore very similar software as you have here can be also used for Peertubes. For instance, take a look at this About page:

https://peertube.linuxrocks.online/about/instance

**Comment by TheKinrar** [comment] 2022-11-21 09:44
Duplicate of #51

**Closed by TheKinrar** 2022-11-21 09:44 UTC

**Comment by mmahmoudian** [comment] 2022-11-21 14:41
Thanks :+1: . Sorry for the duplicate. it was an oversight from my side.
