### ISSUE TITLE
Duplicate instances - www vs root domain

### ISSUE THREAD

**Issue by ineffyble** [TheKinrar/instances#128] opened 2022-11-21 12:14 UTC
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/834880/203051495-e8d566b7-8ae5-4986-9463-04271afe3359.png">

**Comment by TheKinrar** [comment] 2023-02-04 03:12
Duplicate of #75

**Closed by TheKinrar** 2023-02-04 03:12 UTC
Labels: bug
