### ISSUE TITLE
aus.social missing

### ISSUE THREAD

**Issue by flcdrg** [TheKinrar/instances#118] opened 2022-11-05 07:12 UTC
https://aus.social/

(FYI, right this minute I know it is down for a couple of hours while they migrate to a new server)

**Comment by MrGeneration** [comment] 2022-11-14 22:49
The instance can be registered by its owner here:
https://instances.social/admin

**Comment by TheKinrar** [comment] 2022-11-21 09:20
Duplicate of #120

**Closed by TheKinrar** 2022-11-21 09:20 UTC
Labels: bug
